### ISSUE TITLE
클래스의 역할별로 package 를 분리해야 합니다

### ISSUE THREAD

**Issue by callor** [Yeonsu1027/Biz-2023-11-505-java#1]
![image](https://github.com/Yeonsu1027/Biz-2023-11-505-java/assets/23270330/9aed6b28-d195-4960-9e5a-0228055f5b3a)

모든 class 가 같은 package 에 있네요
역할별로 class 를 분리해야 합니다

**Comment by Yeonsu1027** [comment]
다시 분리했습니다
