### ISSUE TITLE
method 는 역할별로 분리해야 합니다

### ISSUE THREAD

**Issue by callor** [Yeonsu1027/Biz-2023-11-505-java#2]
![image](https://github.com/Yeonsu1027/Biz-2023-11-505-java/assets/23270330/fc3be49a-b624-405b-a7a9-3b796ded734c)

점수를 scores 리스트에 추가하는 method
score  리스트에 추가된 성적정보를 출력하는 method

한개의 method 에서는 한가지 일만 수행해야 합니다

모든 것을 printScore() method 에서 처리하려고 하면 안됩니다

**Comment by Yeonsu1027** [comment]
분리해보겠습니다

**Comment by Yeonsu1027** [comment]
분리했습니다
